# Generated by Django 4.1.2 on 2024-03-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_alter_persons_email2_alter_persons_fullname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persons',
            unique_together={('fullname', 'identification')},
        ),
    ]
