CondicionesVulnerablesConst =[
    {
        "name": "DESPLAZADO",
        "opciones": [
            "DESPLAZADO",
            "DESPLAZADO DESPLAZADO",
            "DESPLAZADO CRISTIANAINDÍGENA WIWA",
            "DESPLAZADO-CRISTIANO",
            "DESPLAZADO-COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES",
            "DESPLAZADOINDÍGENA Wayuu",
            "DESPLAZADO INDÍGENA Wayuu",
            "DESPLAZADOINDÍGENA (U´wa)",
            "DESPLAZADO INDÍGENA Achagua",
            "Despojo o abandono forzado de tierras y otros bienes inmuebles",
        ],
        "value": 7
    },
    {
        "name": "CATOLICO",
        "opciones": [
            "CATOLICO",
            "CATÓLICA",
            "CRISTIANO",
            "CATOLICO-INDIGENA",
            "CRITIANA-COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES",
            "CRISTIANA PENTECOSTAL-DESPLAZADO",
            "CATOLICO-COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES",
            "CATOLICO -COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES",
            "CATÓLICA-COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES",
            "CATALOCA-COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES",
            "CATOLICO  COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES",
            "CATOLICOINDÍGENA Wayuu",
            "EVANGELICO",
            "TESTIGO DE JEHOVÁDESPLAZADO",
            "LA CATOLICOINDÍGENA Wayuu",
        ],
        "value": 9
    },
    {
        "name": "AFRODESCENDIENTE",
        "opciones": [
            "AFRODESCENDIENTE",
            "Afrocolombianos DESPLAZADO",
            "Afrocolombianos",
            "AfrocolombianosINDÍGENA Wayuu",
            "Afrocolombianos Homicidio",
            "Afrocolombianos Amenaza a la vida, a la integridad y a la seguridad personal",
            "Afrocolombianos Despojo o abandono forzado de tierras y otros bienes inmuebles",
            "COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES  Raizales",
            "COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES  Afrocolombianos",
            "COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES",
            "COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTESDESPLAZADO",
            "COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES  Palenqueros",
            "COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES  INDÍGENA Wayuu",
            "COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES INDÍGENA Wayuu",
            "COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTESINDÍGENA INDÍGENA Wayuu",
            "Achagua Afrocolombianos DESPLAZADO Achagua Afrocolombianos",
            "Kogui DESPLAZADO Kogui",
            "COMUNIDADES AFROCOLOMBIANAS O AFRODECENDIENTES DESPLAZADO",
        ],
        "value": 3
    },
    {
        "name": "INDIGENA",
        "opciones": [
            "INDÍGENA  INDÍGENA Wayuu",
            "INDIGENA",
            "INDÍGENA Wayuu",
            "INDÍGENA WIWA",
            "INDÍGENA (U´wa)",
            "INDÍGENA Barí",
            "INDÍGENA Andoke",
            "INDÍGENA Achagua",
            "INDÍGENA Awa",
            "INDÍGENA Amorúa",
            "INDÍGENA kankuamo",
            "INDÍGENA Senú",
            "INDÍGENA Wayuu  DESPLAZADO",
            "INDIGENA DESPLAZADO",
            "INDÍGENA Wayuu  DESPLAZADO INDÍGENA Wayuu",
            "INDÍGENA Wayuu  Amenaza a la vida, a la integridad y a la seguridad personal INDÍGENA Wayuu",
            "INDÍGENA WIWA (arzario) DESPLAZADO INDÍGENA WIWA (arzario)",
            "INDÍGENA Wayuu  Homicidio INDÍGENA Wayuu",
            "INDÍGENA Arhuaco",
            "INDÍGENA Wayuu Homicidio",
            "INDÍGENA WIWA (arzario)",
            "INDÍGENA Wayuu  Desaparicion forzada INDÍGENA Wayuu",
            "INDÍGENA Wayuu DESPLAZADO",
            "INDÍGENA Inga",
        ],
        "value": 1
    },
    {
        "name": "DISCAPACITADO",
        "opciones": [
            "DISCAPACITADO",
            "DISCAPACITADO INDÍGENA Wayuu",
        ],
        "value": 8
    },
    {
        "name": "VICTIMA DE VIOLENCIA",
        "opciones": [
            "Desaparicion forzada",
            "Amenaza a la vida, a la integridad y a la seguridad personal",
        ],
        "value": 2
    },
    {
        "name": "OTROS",
        "opciones": [
            "NR",
            "NE",
            "MR",
            "NP",
            "NA",
            "OTRO",
            "CONDICION VULNERABLE",
            "INDIFERENTE",
            "-ROM ? GITANO",
            "GRADO PSTUMO",
            "ZenÃº / senÃº",
            "Homicidio",
            "ROM ? GITANO",
            "Kogui",
            "Lesiones personales",
        ],
        "value": 10
    }
]