# Generated by Django 4.1.2 on 2024-03-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_asistenciaexternos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaexternos',
            name='document',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='asistenciaexternos',
            name='vinculacion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='asistenciaexternos',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='asistenciaexternos',
            name='fullname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='asistenciaexternos',
            name='phone',
            field=models.CharField(default='', max_length=150),
        ),
    ]
