# Generated by Django 4.1.2 on 2024-03-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_asistenciaexternos_document_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciaexternos',
            unique_together={('actividad', 'document')},
        ),
    ]
