# Generated by Django 4.1.2 on 2024-03-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evidencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencias',
            name='archivo',
            field=models.FileField(null=True, upload_to='eventos/%Y/%m/'),
        ),
    ]
